---
- name: Update packages with apt
  apt:
    name: "*"
    state: latest
  when: ansible_facts['os_family'] == "Debian"
- name: Update packages with yum
  yum:
    name: "*"
    state: latest
  when: ansible_facts['os_family'] == "RedHat"
