---
- name: Remove packages with apt
  apt:
    name: "{{ apt_remove }}"
    state: absent
  when: ansible_facts['os_family'] == "Debian"
- name: Install packages with apt
  apt:
    name: "{{ apt_packages }}"
    update_cache: yes
  when: ansible_facts['os_family'] == "Debian"
- name: Remove packages with yum
  yum:
    name: "{{ yum_remove }}"
    state: absent
  when: ansible_facts['os_family'] == "RedHat"
- name: Install packages with yum
  yum:
    name: "{{ yum_packages }}"
  when: ansible_facts['os_family'] == "RedHat"
